### ISSUE TITLE
缩进不一致有影响么

### ISSUE THREAD

**Issue by shawn0915** [luyomo/OhMyTiUP#1]
https://github.com/luyomo/OhMyTiUP/blob/273d215956090b1c9e2077b977da852163d951f1/components/aws/command/root.go#L202-L204
新增命令的缩进是空格，和原来不一致，不知道是否有影响 😜

**Comment by luyomo** [comment]
没影响。 现在代码比较乱。 如果你有什么有意思的架构需要。提个REQUEST哈。 最好和TiDB有关的。 我来验证。

**Comment by shawn0915** [comment]
okay, thanks a lot.
